force-app/main/default/objects/Event_Speaker__c/Event_Speaker__c.object-meta.xml
<CustomObject>
    <label>Event Speaker</label>
    <nameField>
        <label>Event Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Events Speakers</relationshipLabel>
    <relationshipName>Events_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/EventSpeakerTriggerService.cls
public with sharing class EventSpeakerTriggerService {
    public static void onBeforeInsertOrUpdate(List<sObject> objList){
        List<SObject> speakers = [Select Speaker__c from Event_Speaker__C];
        for(SObject ev : objList){
            for(SObject speaker : speakers){
                if(ev.get('Speaker__c') == speaker.get('Speaker__c')){
                    ev.addError('Speaker is not available!'+ ev.get('Speaker__c') + ' ' +speaker.id);
                }
            }
        }
    }
}