force-app/main/default/objects/Event__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event #</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/Event_Speaker__c.object-meta.xml
<CustomObject>
    <label>Event Speaker</label>
    <nameField>
        <label>Event Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Events Speakers</relationshipLabel>
    <relationshipName>Events_Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Events Speakers</relationshipLabel>
    <relationshipName>Events_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/EventSpeakerService.cls
public with sharing class EventSpeakerService {
    public static List<Event_Speaker__c> getSpeakersByEventId(String eventId){
        List<Event_Speaker__c> speakerDataList = [SELECT Speaker__r.Id, Speaker__r.Name, Speaker__r.Email__c,Speaker__r.Phone__c FROM Event_Speaker__c WHERE Event__c = :eventId];
        return speakerDataList;
    }
    public static List<Speaker__c> transformEventSpeakerListToSpeakerList(List<Event_Speaker__c> eventSpeakerList){
        List<Speaker__c> speakerList = new List<Speaker__c>();
        for(Event_Speaker__c ev : eventSpeakerList){
            Speaker__c speaker = new Speaker__c();
            speaker.Id = ev.Speaker__r.Id;
            speaker.Name = ev.Speaker__r.Name;
            speaker.Email__c = ev.Speaker__r.Email__c;
            speaker.Phone__c = ev.Speaker__r.Phone__c;
            speakerList.add(speaker);
        }
        return speakerList;
    }
}