force-app/main/default/objects/Event__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event #</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/EventLocationController.cls
public with sharing class EventLocationController {
    @AuraEnabled(cacheable=true)
    public static List<Location__c> getLocationDataByEventId(String eventId){
        List<Event__c> eventsList = EventLocationService.getLocationByEventId(eventId);
        List<Location__c> locationList = EventLocationService.tranformEventListToLocationList(eventsList);
        if(locationList.size()>0){
            return locationList;
        }
        return null;
    }
}